version: "3.7"
services:
    app:
        build:
            args:
                user: user
                uid: 1000
                context: ./
                dockerfile: Dockerfile
                image: laravel-tickets
                restart: unless-stopped
                working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - tickets
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - tickets
    db:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks:
            - tickets
networks:
    tickets:
        driver: bridge
